name: Auto Web Clock In

on:
  schedule:
    - cron: '30 5 * * 0-4'  # (UTC) == Runs at 8:30 AM BH Time (UTC+3:00)
  workflow_dispatch:      # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: Install requests
        run: pip install requests

      - name: Run WebClockIn script
        run: python WebClockIn.py
        env:
          KEKA_TOKEN: ${{secrets.KEKA_TOKEN}}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
